name: CI Pipeline with slsa

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-backend:
    uses: ebrahimmagdy/github_workflows/.github/workflows/java-build.yml@main
    with:
      working-directory: hello-world-backend

  test-frontend:
    uses: ebrahimmagdy/github_workflows/.github/workflows/angular-build.yml@main
    with:
      working-directory: hello-world-frontend

  build-backend-image:
    uses: ebrahimmagdy/github_workflows/.github/workflows/docker-build-and-push.yml@main
    with:
      image: ${{ format('{0}/hello-world-backend', vars.DOCKER_USERNAME) }}
      context: hello-world-backend
      dockerfile: hello-world-backend/Dockerfile
      push: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


  # build-frontend-image:
  #   needs: test-frontend
  #   uses: slsa-framework/slsa-github-generator/.github/workflows/builder_container-based_slsa3.yml@v1.8.0
  #   permissions:
  #     contents: read
  #     id-token: write
  #   with:
  #     image: ${{ secrets.DOCKER_USERNAME }}/hello-world-frontend
  #     push: true
  #     dockerfile: hello-world-frontend/Dockerfile
  #     context: hello-world-frontend
  #     registry-username: ${{ secrets.DOCKER_USERNAME }}
  #     registry-password: ${{ secrets.DOCKER_PASSWORD }}


