name: CI Pipeline with slsa

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-backend:
    uses: ebrahimmagdy/github_workflows/.github/workflows/java-build.yml@main
    with:
      working-directory: hello-world-backend

  test-frontend:
    uses: ebrahimmagdy/github_workflows/.github/workflows/angular-build.yml@main
    with:
      working-directory: hello-world-frontend

  build-backend-image:
    uses: ebrahimmagdy/github_workflows/.github/workflows/docker-build-and-push.yml@main
    needs: build-backend
    with:
      image: ibrahimmagdy01/hello-world-backend
      context: hello-world-backend
      dockerfile: hello-world-backend/Dockerfile
      push: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


  build-frontend-image:
    uses: ebrahimmagdy/github_workflows/.github/workflows/docker-build-and-push.yml@main
    needs: test-frontend
    with:
      image: ibrahimmagdy01/hello-world-frontend
      context: hello-world-frontend
      dockerfile: hello-world-frontend/Dockerfile
      push: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


